# Generated by Django 5.0.1 on 2024-01-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=155, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category_disc', models.TextField()),
                ('icon_str', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=155, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('item_disc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=10)),
                ('item_img', models.ImageField(default='item.jpg', upload_to='items/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.category')),
            ],
        ),
    ]
