# Generated by Django 5.0.1 on 2024-03-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_str',
            field=models.ImageField(default='hello.png', upload_to='categories/'),
        ),
    ]
