# Generated by Django 5.0.1 on 2024-02-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_contactaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaddress',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
